# wrangler.toml
name = 'iotlol'
main = "src/index.js" # This is your current main file
compatibility_date = "2024-05-18"

# D1 databases definition - MUST be an array
[[d1_databases]]
binding = "dataiot"
database_name = "newiot"
database_id = "8bf6050b-5d7a-49fd-8074-18ade07b9eb1"
# === CRON TRIGGER ADDITION (The essential safety step) ===
# This tells Cloudflare to run the worker every minute.
[triggers]#[[triggers.crons]]
cron = "* * * * *"
