name = 'iotlol'
main = "src/index.js"
compatibility_date = "2024-05-18"

[[d1_databases]]
binding = "dataiot"
database_name = "newiot"
database_id = "8bf6050b-5d7a-49fd-8074-18ade07b9eb1"
[[triggers.crons]]
crons = "* * * * *" 
# CRITICAL FIX: ASSET BINDING
[site]
bucket = "public"

