# wrangler.toml
name = 'iotlol'
main = "src/index.js"
compatibility_date = "2024-06-03"

# D1 databases definition - MUST be an array
[[d1_databases]]
binding = "dataiot"
database_name = "iotbase"
database_id = "06d4d2a7-e9e2-47d6-97c3-9f623aca8f45"
